env:
notifications:
  email: false
  
apt:
    update: true
addons:
    apt:
        sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
            - build-essential
            - software-properties-common
            - zlib1g-dev
            - gcc-7
            - g++-7
            - clang
            - subversion
            - make
            - cmake
            - python
            - libtool
            - libsdl2-2.0-0
            - libsdl2-dev
            - libsdl2-gfx-dev
            - libsdl2-image-2.0-0
            - libsdl2-image-dev
            - libsdl2-ttf-2.0-0
            - libsdl2-ttf-dev

cache:
    apt: true
    
language: node_js
node_js:
    - node

os:
    - linux
sudo: required
dist: trusty
services:
    - docker

before_install:
    - curl -fsSL https://raw.githubusercontent.com/falgon/SrookCppLibraries/master/travis/linux/before_install.sh | bash
    - sudo apt-get -f -y -qq install
    - sudo apt-get -y autoremove

install:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
    - sudo update-alternatives --config gcc
    - docker run -dit --name emscripten -v $(pwd):/src -v /usr/local/include:/include_usr_lib -v /usr/include/c++/7.4.0:/usr/include_lib trzeci/emscripten:sdk-incoming-64bit bash
    - gcc --version
    - clang --version
    - ls /usr/include

script:
    - docker exec -it emscripten make INCLUDE_PATH="/include_usr_lib -I/usr/include_lib" clean debug
    - docker exec -it emscripten make INCLUDE_PATH="/include_usr_lib -I/usr/include_lib" clean app
    - docker exec -it emscripten make INCLUDE_PATH="/include_usr_lib -I/usr/include_lib" -j ${CPU_NUM}
