env:
notifications:
  email: false

apt:
    update: true
cache:
    apt: true
    
language: node_js
node_js:
    - node

os:
    - linux
sudo: required
dist: trusty
services:
    - docker

before_install:
    - export CPU_NUM=$(egrep -c "^processor\s:\s[0-9]+$" /proc/cpuinfo);
    - curl -fsSL https://raw.githubusercontent.com/falgon/SrookCppLibraries/master/travis/linux/before_install.sh | bash
    - sudo apt-get -f -y -qq install
    - sudo apt-get -y -qq install aptitude
    - sudo apt-get -y autoremove

install:
    - sudo apt-get -qq -y install build-essential software-properties-common zlib1g-dev
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -qq update
    - sudo apt-get -qq install gcc-7 g++-7 clang subversion make cmake python libtool zlib1g zlib1g-dev -y
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
    - sudo update-alternatives --config gcc
    - sudo aptitude install -y libsdl2-2.0-0 libsdl-ttf2.0-dev libsdl2-dev
    - docker run -dit --name emscripten -v $(pwd):/src -v /usr/local/include:/usr/local/include -v /usr/include:/usr/include trzeci/emscripten:sdk-incoming-64bit bash

script:
    - docker exec -it emscripten make clean debug
    - docker exec -it emscripten make clean app
    - docker exec -it emscripten make -j ${CPU_NUM}
