env:
notifications:
  email: false
  
apt:
    update: true

cache:
    apt: true
    
language: node_js
node_js:
    - node

os:
    - linux
sudo: required
dist: trusty
services:
    - docker

before_install:
    - curl -fsSL https://raw.githubusercontent.com/falgon/SrookCppLibraries/master/travis/linux/before_install.sh | bash
    - sudo apt-get -f -y -qq install
    - sudo apt-get -y autoremove

install:
    - docker run -dit --name emscripten -v $(pwd):/src --entrypoint ./docker_entry.sh trzeci/emscripten:sdk-incoming-64bit bash

script:
    - docker exec -it emscripten make clean debug
    - docker exec -it emscripten make clean app
    - docker exec -it emscripten make -j ${CPU_NUM}
