env:
notifications:
  email: false
  
apt:
    update: true

cache:
    apt: true
    
language: node_js
node_js:
    - node

os:
    - linux
sudo: required
dist: trusty
services:
    - docker

before_install:
    - export CPU_NUM=$(egrep -c "^processor\s:\s[0-9]+$" /proc/cpuinfo);

install:
    - chmod +x docker_entry.sh
    - docker run -dit --name emscripten -v $(pwd)/.travis:/src bash
    - docker exec -it emscripten ./docker_entry.sh

script:
    - docker exec -it emscripten make clean debug
    - docker exec -it emscripten make clean app
    - docker exec -it emscripten make -j ${CPU_NUM}
