env:
notifications:
  email: false
  
apt:
    update: true

cache:
    apt: true
    
language: node_js
node_js:
    - node

os:
    - linux
sudo: required
dist: trusty
services:
    - docker

before_install:
    - export CPU_NUM=$(egrep -c "^processor\s:\s[0-9]+$" /proc/cpuinfo);

install:
    - chmod +x .travis/docker_entry.sh
    - docker run -dit --name emscripten -v $(pwd)/.travis:/mnt -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
    - docker exec -it emscripten /mnt/docker_entry.sh

script:
    - docker exec -it emscripten make CXXFLAGS="-D__linux__ -D_REENTRANT -std=c++1z -Wall -Wextra -pedantic" INCLUDE_PATH=$(cat -n `pwd`/.travis/include_path) clean app
    - docker exec -it emscripten make CXXFLAGS="-D__linux__ -D_REENTRANT -std=c++1z -Wall -Wextra -pedantic" INCLUDE_PATH=$(cat -n `pwd`/.travis/include_path) -j ${CPU_NUM}
